language: python

notifications:
  irc:
    channels:
      - "irc.oftc.net#tor-bots"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
    on_success: always
    on_failure: always
  email:
    recipients:
      - isis@torproject.org
      - sysrqb@torproject.org
    on_success: never
    on_failure: change

python:
  - "2.7"
  - "pypy"

addons:
  hosts:
    - bridges.torproject.org

env:
  global:
    - LEEKSPIN_VERSION=0.1.4
    - COVERAGE_VERSION=3.7.1
    - COVERALLS_VERSION=0.4.2
    - SURE_VERSION=1.2.2
  matrix:
    - TWISTED_VERSION=13.2.0 PYOPENSSL_VERSION=0.13.1

matrix:
  include:
    - python: "2.7"
      env: TWISTED_VERSION=14.0.0 PYOPENSSL_VERSION=0.14
  allow_failures:
    - python: "pypy"
  fast_finish: true

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -qq --no-install-suggests --no-install-recommends build-essential openssl sqlite3 libgpgme11 libgpgme11-dev python-dev python-setuptools
  - pip install -q -r .travis.requirements.txt
  - pip install -q --no-use-wheel leekspin==$LEEKSPIN_VERSION sure==$SURE_VERSION
  - pip install -q --no-use-wheel coverage==$COVERAGE_VERSION coveralls==$COVERALLS_VERSION
  - pip install -q --no-use-wheel Twisted==$TWISTED_VERSION pyOpenSSL==$PYOPENSSL_VERSION
  - make install

script:
  - make coverage-test

after_success:
  - coveralls
