language: python

notifications:
  irc:
    channels:
      - "irc.oftc.net#tor-bots"
    on_success: always
    on_failure: always
  template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - "Build details : %{build_url}"
  email:
    recipients:
      - isis@torproject.org
      - sysrqb@torproject.org
    on_success: never
    on_failure: change

addons:
  hosts:
    - bridges.torproject.org

before_install:
  - sudo apt-get update

python:
  - "2.7"

install:
  - sudo apt-get install --no-install-suggests --no-install-recommends build-essential openssl sqlite3 libgpgme11 libgpgme11-dev python-dev python-setuptools
  - pip install -r requirements.txt
  - pip install --no-use-wheel leekspin==0.1.3 coverage==3.7.1 coveralls==0.4.2 sure==1.2.2
  - make install

script:
  - make coverage-test

after_success:
  - coveralls
